### PR TITLE
config: use platform specific default for `Api`

### LINKED ISSUE #1586: Android (egl) example picks wrong gl version
The crash of #1584 is resolved on master, but the template builder still only receives a config with GLES1 instead of the available 3.2 (as the official Java example does), causing no functionality to be available, just keeps repeating:
```
libEGL  : called unimplemented OpenGL ES API
```
It seems this limited config is picked because glutin-winit/src/lib.rs build() function does not initialize a raw window handle for egl.
Then in api/egl/display.rs new() the comment says it needs raw_display or EGL_DEFAULT_DISPLAY is used which is not recommended.

### PR DESCRIPTION
**Pull request by kchibisov**
Avoid pure ES1 configs with EGL by default. The old default behavior could be restored by using the `Api::empty`.

Fixes #1586.

### CODE REVIEW

File: glutin/src/config.rs [hunk 1]
```diff
@@ -166,7 +166,14 @@ impl ConfigTemplateBuilder {
 
     /// The set of apis that are supported by configuration.
     ///
-    /// By default api isn't specified when requesting the configuration.
+    /// The default is specific based on the used API. If you
+    /// want to do config filterig based in [`Api`] yourself use [`Api::empty`].
```
Comment (MarijnS95) [inline glutin/src/config.rs:170]:
```suggestion
    /// want to do config filtering based on the [`Api`] yourself, use [`Api::empty`].
```

File: glutin/src/config.rs [hunk 2]
```diff
@@ -166,7 +166,14 @@ impl ConfigTemplateBuilder {
 
     /// The set of apis that are supported by configuration.
     ///
-    /// By default api isn't specified when requesting the configuration.
+    /// The default is specific based on the used API. If you
```
Comment (MarijnS95) [inline glutin/src/config.rs:169]: Not quite sure how to word this because we have the `Api` flag here which is different from the EGL/GLX/WGL/CGL "API", but they are named the same... Wikipedia calls EGL a "native graphics platform interface".

```suggestion
    /// The default [`Api`] depends on the used graphics platform interface. If you
```

But not really liking that yet.

File: glutin/src/config.rs [hunk 3]
```diff
@@ -166,7 +166,14 @@ impl ConfigTemplateBuilder {
...
+    /// want to do config filtering based on the [`Api`] yourself, use [`Api::empty`].
+    ///
+    /// # Api-specific
```
Comment (MarijnS95) [inline glutin/src/config.rs:172]:
```suggestion
    /// # Api-specific defaults
```

Comment (kchibisov) [reply glutin/src/config.rs:172]: it's not only about defaults though, we just have a `Api-specific` section which is common with the rest.

As you can see the `GLX` line says that you always have OPENGL regardless of what you do.

File: glutin/src/config.rs [hunk 4]
```diff
@@ -164,9 +164,16 @@ impl ConfigTemplateBuilder {
...
+    ///
+    /// **EGL:** - [`Api::GLES2`] bit is set by default to avoid matching
+    /// [`Api::GLES1`] configs.
+    /// **GLX/WGL/CGL:** - [`Api::OPENGL`] is always present in the result.
```
Comment (MarijnS95) [inline glutin/src/config.rs:176]: Does rustdoc render this nicely btw? I have a hunch the `-` has to be at the beginning to get an _Unordered List_ otherwise this just becomes one line/paragraph?

File: glutin/src/config.rs (hunk 2 above)
Comment (kchibisov) [reply glutin/src/config.rs:169]: I think it's fine, at least it's better than what we had.

File: glutin/src/config.rs (hunk 4 above)
Comment (kchibisov) [reply glutin/src/config.rs:176]: You're right, there should be `-` to form a list.

Comment (MarijnS95) [reply glutin/src/config.rs:176]: image
Yup, it doesn't like it:

```suggestion
    /// - **EGL:** [`Api::GLES2`] bit is set by default to avoid matching
    /// [`Api::GLES1`] configs.
    /// - **GLX/WGL/CGL:** [`Api::OPENGL`] is always present in the result.
```

**Review by MarijnS95 — APPROVED** [review]
Looks and sounds good, after fixing the unordered-list formatting 🎉
